### ISSUE TITLE
Work your Magic/Voodoo on ZD2 effects (for G1Four, etc)?

### ISSUE THREAD

**Issue by mungewell** [ELynx/zoom-fx-modding#4]
I see that your 'process' is to patch particular bytes in the ZDL effects, I am wondering whether the same process could also be applied to the ZD2 effects of the G1Four, G3, G5, etc pedals.

There does not seem to be a 'LINESEL' effect, I have a list of all known ZD2 effects here:
https://github.com/mungewell/zoom-zt2/blob/master/zoom_fx/master.txt

I also have tools for expanding/exporting various sections of the ZD2 to code/bitmap/text/XML:
https://github.com/mungewell/zoom-zt2/blob/master/decode_effect.py

The code section is a ELF binary, compiled for the TMS320C67x, I am working on finding a 'free' disassembler for those...

**Comment by ELynx** [comment]
Sure. I think I decompiled some ZD2s, some `poly`something or not was asked on Reddit. I think same toolchain worked.

I did not see LINESEL, I think it is handled by firmware independently, but that is just a hunch.

So to that, code section should be decompile-able with same tools I use. Worked for me.

**Comment by ELynx** [comment]
Any other info we can discuss? If so, please let me know.

Otherwise I will close the issue some time soon.

Not closing the communication though, OFC. Ping me any way.
